export type SpellLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

export const MAGIC_USER_SPELLS: Record<SpellLevel, readonly string[]> = {
  1: [
    "Charm Person",
    "Detect Magic",
    "Floating Disc",
    "Hold Portal",
    "Light",
    "Magic Missile",
    "Protection from Evil",
    "Read Languages",
    "Read Magic",
    "Shield",
    "Sleep",
    "Ventriloquism",
  ],
  2: [
    "Continual Light",
    "Detect Evil",
    "Detect Invisible",
    "ESP",
    "Invisibility",
    "Knock",
    "Levitate",
    "Locate Object",
    "Mirror Image",
    "Phantasmal Force",
    "Web",
    "Wizard Lock",
  ],
  3: [
    "Clairvoyance",
    "Dispel Magic",
    "Explosive Runes",
    "Fire Ball",
    "Fly",
    "Haste",
    "Hold Person",
    "Infravision",
    "Invisibility 10' Radius",
    "Lightning Bolt",
    "Protection from Evil 10' Radius",
    "Protection from Normal Missiles",
    "Slow",
    "Water Breathing",
  ],
  4: [
    "Charm Monster",
    "Confusion",
    "Dimension Door",
    "Fire Shield",
    "Fumble",
    "Ice Storm",
    "Minor Globe of Invulnerability",
    "Remove Curse",
    "Stoneskin",
    "Wall of Fire",
    "Wall of Ice",
    "Wizard Eye",
  ],
  5: [
    "Animate Dead",
    "Cloudkill",
    "Cone of Cold",
    "Feeblemind",
    "Hold Monster",
    "Magic Jar",
    "Passwall",
    "Telekinesis",
    "Teleport",
    "Wall of Force",
    "Wall of Iron",
    "Wall of Stone",
  ],
  6: [
    "Anti-Magic Shell",
    "Death Spell",
    "Disintegrate",
    "Geas",
    "Invisible Stalker",
    "Lower Water",
    "Move Earth",
    "Part Water",
    "Project Image",
    "Reincarnation",
    "Stone to Flesh",
  ],
  7: [
    "Create Normal Monsters",
    "Delayed Blast Fireball",
    "Lore",
    "Magic Door",
    "Mass Invisibility",
    "Power Word Stun",
    "Reverse Gravity",
    "Statue",
    "Summon Object",
    "Sword",
    "Teleport any Object",
  ],
  8: [
    "Clone",
    "Create Magical Monsters",
    "Dance",
    "Explosive Cloud",
    "Force Field",
    "Mass Charm",
    "Mind Barrier",
    "Permanent",
    "Polymorph Any Object",
    "Power Word Blind",
    "Symbol",
    "Travel",
  ],
  9: [
    "Create Any Monster",
    "Gate",
    "Heal",
    "Immunity",
    "Maze",
    "Meteor Swarm",
    "Power Word Kill",
    "Prismatic Wall",
    "Shape Change",
    "Survival",
    "Time Stop",
    "Wish",
  ],
};

export const CLERIC_SPELLS: Record<SpellLevel, readonly string[]> = {
  1: [
    "Cure Light Wounds",
    "Detect Evil",
    "Detect Magic",
    "Light",
    "Protection from Evil",
    "Purify Food and Water",
    "Remove Fear",
    "Resist Cold",
  ],
  2: [
    "Bless",
    "Find Traps",
    "Hold Person",
    "Know Alignment",
    "Resist Fire",
    "Silence 15' Radius",
    "Snake Charm",
    "Speak with Animal",
  ],
  3: ["Continual Light", "Cure Disease", "Growth of Animal", "Locate Object", "Remove Curse", "Striking"],
  4: [
    "Create Water",
    "Cure Serious Wounds",
    "Dispel Magic",
    "Neutralize Poison",
    "Protection from Evil 10' Radius",
    "Speak with Plants",
    "Sticks to Snakes",
  ],
  5: ["Commune", "Create Food", "Dispel Evil", "Insect Plague", "Quest", "Raise Dead", "Truesight"],
  6: [
    "Aerial Servant",
    "Animate Objects",
    "Barrier",
    "Create Normal Animals",
    "Cure Critical Wounds",
    "Find the Path",
    "Speak with Monsters",
    "Word of Recall",
  ],
  7: ["Earthquake", "Holy Word", "Raise Dead Fully", "Restoration", "Resurrection", "Survival", "Travel", "Wish"],
  8: [],
  9: [],
};

export const DRUID_SPELLS: Record<SpellLevel, readonly string[]> = {
  1: [
    "Detect Danger",
    "Faerie Fire",
    "Locate",
    "Predict Weather",
  ],
  2: [
    "Heat Metal",
    "Obscure",
    "Produce Fire",
    "Warp Wood",
  ],
  3: [
    "Call Lightning",
    "Hold Animal",
    "Protection from Poison",
    "Water Breathing",
  ],
  4: [
    "Control Temperature",
    "Plant Door",
    "Protection from Lightning",
    "Summon Animals",
  ],
  5: [
    "Anti-Plant Shell",
    "Pass Plant",
    "Stoneskin",
    "Wall of Thorns",
  ],
  6: [
    "Anti-Animal Shell",
    "Summon Weather",
    "Transport Through Plants",
    "Turn Wood",
  ],
  7: [
    "Creeping Doom",
    "Metal to Wood",
    "Summon Elemental",
    "Weather Control",
  ],
  8: [],
  9: [],
};

